### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by wangzongle** [ungeeked/Ozone#1]
Oneplus 5 with h2os oreo open beta 2
bug: When I select the background color as aosp grey and set QS background as default (use background color) , then apply this theme , the QS background will be black instead of aosp grey.

and suggestion in statusbar:
1.could you chage the vpn icon as the ssr's icon like the left one in below
2.could you hide the 1x signal icon just save the 4g icon in below pic.
![972414181](https://user-images.githubusercontent.com/10363352/34567542-a5d16b04-f19d-11e7-920b-d147d8b344c4.jpg)

**Comment by ungeeked** [comment]
1) H2OS is not officially supported. I may still be able to fix the issue if you can send me the OPSystemUI.apk Also make sure that you don't have more than one systemui overlays installed.

2) What is SSR? The key icon for VPN is the standard one. Won't change it because not everyone uses SSR. I already have a "Hide VPN" option which will hide it and you'll only have the SSR option. 

3) For the 1x icon, I'd be needing the OPSystemUI.apk. What does it denote anyway?

**Comment by wangzongle** [comment]
[OPSystemUI.zip](https://github.com/ungeeked/Ozone/files/1603636/OPSystemUI.zip)

**Comment by wangzongle** [comment]
and the 1x icon denote cdma signal ,
thank you.

**Comment by wangzongle** [comment]
something more , could you add a option to change the row of QS icon

**Comment by ungeeked** [comment]
@wangzongle Not possible using substratum

**Comment by ungeeked** [comment]
I have attempted to fix issue 1 and 3. You'll find an option to hide CDMA icon in statusbar overlay. I have no way to test this so attaching the apk. If issue is resolved, the fix will be available in next PS update

[Ozone_test.zip](https://github.com/ungeeked/Ozone/files/1622710/Ozone_test.zip)

**Comment by wangzongle** [comment]
sorry,maybe I did not express my meaning well,I said "hide" mean to replace
the two small triangles to one big as a normal 4g signal icon.
your solution here is not good-looking as stock.
transform the first one to the second one below,please.


2018-01-11 21:23 GMT+08:00 Prashant <notifications@github.com>:

**Comment by ungeeked** [comment]
@wangzongle Try this 
[Ozone_test2.zip](https://github.com/ungeeked/Ozone/files/1623013/Ozone_test2.zip)

**Comment by wangzongle** [comment]
no change

2018年1月11日 22:38，"Prashant" <notifications@github.com>写道：

**Comment by ungeeked** [comment]
Closing this issue. It is fixable however there are no available drawables inside OPsystemUI to replace the stat_sys_signal*stacked* drawables (in drawable-xxhdpi). Anyone planning to fix this in future will have to find proper icons from some different ROM

**Comment by wangzongle** [comment]
why not use build-in 4g icon replace the 4g-and-1x icon instead of adding a
new one into.

2018年1月11日 22:54，"Prashant" <notifications@github.com>写道：

**Comment by ungeeked** [comment]
@wangzongle The available drawables don't have 3G/4G labels like the stacked icons

**Comment by wangzongle** [comment]
My last phone is nexus 5x,it can normally show 3g and 4g lables,if I can
provide the systemUI.apk,can you have a try again ?

2018年1月12日 13:55，"Prashant" <notifications@github.com>写道：

**Comment by ungeeked** [comment]
On most Androids (including oneplus) the 3G/4G /LTE label is a separate drawable. However when you are using CDMA, the stacked icons get activated. These icons have the signal strength and label in same drawable. I need a similar drawable with correct dimensions to replace

**Comment by wangzongle** [comment]
Nexus5x_8.1.0_SystemUI.zip is form Google factory,Mokee_7.1.2_SystemUI.zip is form a rom patched for OP5,both can normally show.
[Mokee_7.1.2_SystemUI.zip](https://github.com/ungeeked/Ozone/files/1625103/Mokee_7.1.2_SystemUI.zip)
[Nexus5x_8.1.0_SystemUI.zip](https://github.com/ungeeked/Ozone/files/1625104/Nexus5x_8.1.0_SystemUI.zip)
