### ISSUE TITLE
Different accent in app drawer

### ISSUE THREAD

**Issue by SypherRS** [ungeeked/Ozone#1]
The app drawer has pink accents but other UI elements have white which I picked.

Oneplus 3T (A3003), Android 8.0.0 - OOS beta 23
\\Edit: Now I'm on OOS Beta 23, but problem still persists

Normal white in Quick Settings
![screenshot_20180316-225013](https://user-images.githubusercontent.com/37458817/37553684-1ba61994-29cd-11e8-82c0-166a2b3c0239.png)

Pink in App Drawer
![screenshot_20180316-225020](https://user-images.githubusercontent.com/37458817/37553683-17d4d79c-29cd-11e8-85f4-1d9276d1a02b.png)

![screenshot_20180316-225053](https://user-images.githubusercontent.com/37458817/37553674-ea26aee2-29cc-11e8-9546-7a068d2aa403.png)

Pink in shortcuts too
![screenshot mar 17 2018 10_26_48](https://user-images.githubusercontent.com/37458817/37553731-f90c3ee4-29cd-11e8-943c-bfcb26cd8fdd.png)

**Comment by ungeeked** [comment]
Make sure launcher overlay is installed
Make sure you have selected ozone accent in settings > display
Reboot phone

If the issue still persists, attach a screenshot of substratum "manager" tab

**Comment by SypherRS** [comment]
Luck = 0
![screenshot_20180317-140701](https://user-images.githubusercontent.com/37458817/37556666-72d0f140-29f9-11e8-8b42-38b504a2aa9a.jpg)
