### ISSUE TITLE
Accent color in oneplus launcher is not changing!

### ISSUE THREAD

**Issue by xBioK1ngz** [ungeeked/Ozone#2]
Hello people. I have a big problem. My accent color in the oneplus launcher is not changing. I have a oneplus 5. I changed my accent color to red. It changes everywhere expect the launcher. Please help!

**Comment by ungeeked** [comment]
I have added some fixes for launcher https://github.com/ungeeked/Ozone/commit/1630db1536339f943691a6e52ad2176647761410
